### ISSUE TITLE
Scrum Report #2

### ISSUE THREAD

**Issue by WantingLi816** [dburenok/cpsc-455-project#17]
What did you work on this past iteration (2 weeks)?

- Explore existing MUI components and templates

- Read documentation for Berry template

- Explore the components within the template and modify them to fit our project

What were any major issues/challenges you ran into?

- Project failed to build after integrating the template in.

- Released API key by accident in a commit. 

What do you plan to work on for this coming iteration (2 weeks)?

- Develop user stories to help define clear workflows

- Look into the default state of the reducer

**Comment by dburenok** [comment]
What did you work on this past iteration (2 weeks)?
* Implemented a simple map with react-map-gl library
* Read react-map-gl documentation
* Created a bus stop scraper to provide us with data which we will use in displaying bus routes

What were any major issues/challenges you ran into?
* Choosing a mapping library was difficult as a number of them are not compatible with current version of React

What do you plan to work on for this coming iteration (2 weeks)?
* Solidifying our front-end and implementing basic search functionality
* Become more familiar with MUI template

**Comment by brendonson** [comment]
What did you work on this past iteration (2 weeks)?

- Created user stories that matched the user workflow to draw UI mock ups.

What were any major issues/challenges you ran into?

- Knowing what features the users would need/want and implementing them in a user friendly manner and easily developable

What do you plan to work on for this coming iteration (2 weeks)?

- creating components for the front end

**Comment by dennis-fan** [comment]
What did you work on this past iteration (2 weeks)?
+ Merged basic react app framework
+ Started database design based on initial API 
What were any major issues/challenges you ran into?
+ We were not fully clear on the user design - so we have decided to break down user stories to help 
What do you plan to work on for this coming iteration (2 weeks)?
+ DB design and begin API
+ Iron out front-end design
