### ISSUE TITLE
Scrum Report #1

### ISSUE THREAD

**Issue by brendonson** [dburenok/cpsc-455-project#2]
1. Worked on designing the UI and creating mockups
2. Finding the creative direction/inspiration that fits our project for the UI mockups
3. Complete the mockups and start coding

**Comment by WantingLi816** [comment]
What I have done:
1. Clarify some terms and concepts used in the project progress
2. Provide ideas on web interface design
What I will do:
1. Work on assignment 2 and get started on the project
What I was stuck on:
1. finding appropriate and fun project ideas

**Comment by dburenok** [comment]
1. Facilitated the selection of our project idea and outlined the requirements in PP1. Prototyping with a few different mapping libraries
2. No major challenges except our 5th team member exiting the class
3. Splitting up the work between our group members. We aim to get most of the basic requirements done (except "Deploy the app (front-end and back-end) onto the web") and have a working map UI with real Translink data

**Comment by dennis-fan** [comment]
Dennis Fan

1. What did you work on this past iteration (2 weeks)? 
- Read documentation for Translink API
- Explore prior art of translink apps to get ideas for our design
2. What were any major issues/challenges you ran into?
- Finding a 5th team-mate
3. What do you plan to work on for this coming iteration (2 weeks)? 
- Look into API development for web application
- Look into polling Translink API to gather initial dataset of bus arrival times
- Sketch mobile interface for mobile webpage
