### ISSUE TITLE
Scrum Report 4

### ISSUE THREAD

**Issue by WantingLi816** [dburenok/cpsc-455-project#31]
Name: Lisa Li

What did you work on this past iteration?

-  Went over our implementation and made a list of to-dos.

What do you plan to work on for this coming iteration (3 weeks)?

- Look into search bar and related features in mobile view

- Work on bus-capacity reporting feature

**Comment by dburenok** [comment]
Name: Dmitriy Burenok

What did you work on this past iteration?
* Setting up a basic back-end server
* Implementing the bus stop scraper and route builder scripts

What do you plan to work on for this coming iteration (3 weeks)?
* Show buses on map when user clicks a bus stop
* Show estimates in the sidebar when user clicks a bus stop

**Comment by dennis-fan** [comment]
Name: Dennis

What did you work on this past iteration?
+ Setting up REST routes for BE 
+ Integrating atlas calls into Routes
What do you plan to work on for this coming iteration (3 weeks)?
+ Adding bus level estimate data into DB
